name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      run: go build -v ./single_thread_blocking_io && go build -v ./multi_thread_blocking_io && go build -v ./non_blocking_busy_waiting && go build -v ./single_thread_event_loop

    - name: Test
      run: go test -v ./single_thread_blocking_io/... && go test -v ./multi_thread_blocking_io/... && go test -v ./non_blocking_busy_waiting/... && go test -v ./single_thread_event_loop/...
