name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      run: go build -v ./single_threaded_blocking_io && go build -v ./multi_threaded_blocking_io && go build -v ./non_blocking_busy_waiting

    - name: Test
      run: go test -v ./single_threaded_blocking_io/... && go test -v ./multi_threaded_blocking_io/... && go test -v ./non_blocking_busy_waiting/...
